# Generated by Django 4.2.19 on 2025-03-18 02:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Due_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_name', models.CharField(max_length=200, verbose_name='Due Name')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Student Image')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='Staff Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Id')),
                ('mobile', models.CharField(max_length=30, verbose_name='Mobile Num')),
                ('degree', models.CharField(max_length=200, verbose_name='Degree')),
                ('dept', models.CharField(max_length=200, verbose_name='Department')),
                ('image', models.FileField(null=True, upload_to='product/', verbose_name=' Image')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Username')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='Password')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('city', models.CharField(max_length=300, verbose_name=' City')),
                ('address', models.TextField(max_length=2000, verbose_name=' Address')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255, verbose_name='Student Name')),
                ('student_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Student Id')),
                ('email_id', models.EmailField(max_length=255, verbose_name='Email Id')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Number')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('degree', models.CharField(max_length=200, verbose_name='Degree')),
                ('dept', models.CharField(max_length=200, verbose_name='Department')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('state', models.CharField(default='Tamil Nadu', max_length=100, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('image', models.FileField(null=True, upload_to='documents/', verbose_name='Student Image')),
                ('face_data', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, verbose_name='Student Id')),
                ('amount', models.CharField(max_length=100, verbose_name='Amount(Rs)')),
                ('due_date', models.DateField()),
                ('due_status', models.CharField(choices=[('', 'Select'), ('Paid', 'Due Paid'), ('Not Paid', 'Not Paid')], max_length=200, verbose_name='Due Status')),
                ('msg', models.TextField(max_length=2000, verbose_name='Message')),
                ('due_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.due_type')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Alert_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, verbose_name='Student Id')),
                ('send_date', models.DateField(default=datetime.datetime(2025, 3, 18, 2, 58, 20, 232548, tzinfo=datetime.timezone.utc))),
                ('amount', models.CharField(max_length=100, verbose_name='Due Amount')),
                ('msg', models.TextField(max_length=2000, verbose_name='Message')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff_detail')),
            ],
        ),
    ]
